---
version: '3.4'

services:
  odinapi:
    environment:
      - PGHOST=postgresql
      - PGDBNAME=odin
      - PGUSER=odinop
      - PGPASS=odinop
      - SECRET_KEY=myseeecretzzzzzz
    image: docker2.molflow.com/odin_redo/odin_api:latest
    ports: 
      - 5000
    volumes:
      - ./data/vds-data:/vds-data
      - ./data/apriori:/var/lib/odindata/apriori
      - ./data/vds-data/SMRhdf/Qsmr-2-1/:/odin-smr-2-1-data
      - ./data/ptz-data/:/var/lib/odindata
      - ./data/vds-data/OSIRIS_Level2/:/osiris-data
      - ./data/ptz-data/ERA-Interim:/var/lib/odindata/ECMWF
    links:
      - postgresql
      - level2db

  postgresql:
    image: docker2.molflow.com/odin_redo/odin_db:latest

  level2db:
    image: mongo

  microq:
    image: docker2.molflow.com/devops/microq:latest
    ports: 
      - 5000
    environment:
      - USERVICE_DATABASE_URI=mysql+pymysql://testuser:secret@mysqlhost/smr
      - USERVICE_ADMIN_USER=admin
      - USERVICE_ADMIN_PASSWORD=sqrrl
    links:
      - mysqlhost

  mysqlhost:
    build: microq-db
    environment:
      - MYSQL_ROOT_PASSWORD=empty
      - MYSQL_DATABASE=smr
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=secret
